export {default as Splash} from './Splash';
export {default as FindDoctor} from './FindDoctor';
export {default as PatientProfile} from './PatientProfile';
export {default as ReservationCalendar} from './ReservationCalendar';
export {default as Login} from './Login';
export {default as DoctorCalendar} from './DoctorCalendar';
export {default as DoctorProfile} from './DoctorProfile';
export {default as DoctorAvailablities} from './DoctorAvailablities';
export {default as SessionDetail} from './SessionDetail';
